修复编译错误： error TS2345: Argument of type '{ data: any[]; xField: string; yField: string; slider: {}; appendPadding: number; legend: { position: string; }; } & { colorField: string; isStack: boolean; maxAngle: number; }' is not assignable to parameter of type 'RadialBarOptions'.   Types of property 'legend' are incompatible.     Type '{ position: string; }' is not assignable to type 'Legend'.
(cherry picked from commit cacb6bc1bcd74853460da854b0af3db3ae5311de)